### ISSUE TITLE
The plugin works well in paint.net, but I tried in my app and got InvalidFile

### ISSUE THREAD

**Issue by sati32** [0xC0000054/pdn-heicfiletype-plus#2]
I tried this:

		HEIFInterface			heifInterface;

		if (heifInterface.isValid())
		{
			heif_context	*context;

			context = heifInterface.createContext();

			if (context)
			{
				IOCallbacks	fileIO;
				Status		stat;

				_myFile = file;
				fileIO.GetPosition = MyGetPosition;
				fileIO.GetSize = MyGetSize;
				fileIO.Read = MyRead;
				fileIO.Seek = MySeek;
				fileIO.Write = MyWrite;

				stat = heifInterface.loadFileIntoContext(context, &fileIO);

but stat gives always an InvalidFile.
Do you know why?

**Comment by 0xC0000054** [comment]
My only guess is that you may need to seek to the beginning of the file before calling `loadFileIntoContext`.

**Comment by sati32** [comment]
Thank you for your help. But this is not the solution. My file callbacks are called GetPosition and returns 0, GetSize and Read (4 Bytes and gives the first 4 Bytes of the file).
I will try to check the source of LibHeic.

**Comment by sati32** [comment]
OK, the problem was my Read-Callback function. It has to return "0" for no error, not the amount of bytes read, as expected.

**Comment by sati32** [comment]
Works fine now.
May I ask if there is a way to get 16 bit per channel instead of 8?
Is there a way to get data without alpha or is there a way to detect if alpha is present?

**Comment by 0xC0000054** [comment]
You would have to modify the C++ wrapper code to add those features.

Paint.NET uses 8-bit RGBA as its native image format, so the C++ wrapper code used by this plugin only supports that format.
There was no point in adding features to the wrapper that Paint.NET does not support.
