### ISSUE TITLE
Error while open HEIC file

### ISSUE THREAD

**Issue by rUp3r** [0xC0000054/pdn-heicfiletype-plus#3]
paint.net 4.3.10 
There was an error while opening the file.

Attached the exception log;

[exception.log](https://github.com/0xC0000054/pdn-heicfiletype-plus/files/8476474/exception.log)

**Comment by 0xC0000054** [comment]
The exception log did not attach correctly, it is just a link to this issue.

**Comment by rUp3r** [comment]
now uploaded

**Comment by 0xC0000054** [comment]
The error log indicates that the HEIC file is invalid.
Could you zip the file and attach it to this issue?

**Comment by rUp3r** [comment]
[issue - Copy.zip](https://github.com/0xC0000054/pdn-heicfiletype-plus/files/8484972/issue.-.Copy.zip)

**Comment by 0xC0000054** [comment]
That file is a JPEG with a HEIC file extension.
