### ISSUE TITLE
files created with 4:4:4 and 4:2:2 subsampling cannot be opened

### ISSUE THREAD

**Issue by erazortt** [0xC0000054/pdn-heicfiletype-plus#5]
Saving files with 4:4:4 and 4:2:2 chroma subsampling creates files which cannot be opened by paint.net itself.
This is irrespective of any other settings, I think I tested all combinations. Using newest version of paint.net (4.3.11).

I also attached a sample file, which was a newly created 1200x900 of white: [Untitled.zip](https://github.com/0xC0000054/pdn-heicfiletype-plus/files/9050156/Untitled.zip)

**Comment by 0xC0000054** [comment]
That file opens fine for me in paint.net 4.3.11 with HeicFileTypePlus version 1.0.6.
I also tested the plugin, and it is working for me when saving and loading images.

**Comment by erazortt** [comment]
hm.. after restarting it now also works for me..
