### ISSUE TITLE
Rename LICENSE..txt to LICENSE.txt for releases

### ISSUE THREAD

**Issue by Crystal-RainSlide** [0xC0000054/pdn-heicfiletype-plus#7]
No big deal, it's just me reached a `LICENSE..txt` when searching my disk for filenames that contains `..`, and reached here, and confirmed the releases really has a `LICENSE..txt`, although this repo has a `LICENSE.txt`.

You may want to fix this if there is no reason for a `LICENSE..txt`.

**Comment by 0xC0000054** [comment]
This is fixed for the next release.
