### ISSUE TITLE
File size when saving is much larger than original

### ISSUE THREAD

**Issue by veqryn** [0xC0000054/pdn-heicfiletype-plus#8]
My Samsung Galaxy S21 takes photos in heic format.  On average, they are around 1.5 MB large.
If I open them in paint.net with this plugin, then save them again, whether I change anything or not, the saved size is about 5 MB.
In order to get a similar size as the original, I have to put the vague quality setting at around 60%.
Is this potentially a bug or something that could be improved?
Is this all related to the quality setting?
Is there any way to see the quality setting of the original heic image?
Is there any way to edit a heic image in a way that preserves both the original quality and the original file size?  For example, if the only change I am making are cropping, I feel like the image shouldn't have to lose quality and should also decrease in file size or stay the same size at worst.

**Comment by 0xC0000054** [comment]
>  Is this potentially a bug or something that could be improved?

I do not think it is a bug.

>  Is this all related to the quality setting?

The quality slider, Chroma Subsampling, Encoding Speed / Quality and possibly other settings can affect the file size of the output image.

A Chroma Subsampling value of `4:2:0 (Best Compression)` will produce the smallest file size, at the expense of potentially reducing image quality.
The slower Encoding Speed / Quality options may produce a smaller image, at the expense of taking longer to save.

> Is there any way to see the quality setting of the original heic image?

Not as far as I know. Even if this was possible the information would only be relevant for that specific encoder.

> Is there any way to edit a heic image in a way that preserves both the original quality and the original file size?

I do not know.
